function plot_gl_regr_beta(input,params)
% % plot_gl_regr_beta %
%PURPOSE:   Plot the fitted parameters from GLM analysis
%AUTHORS:   AC Kwan 170901
%
%INPUT ARGUMENTS
%   input:        Structure generated by gl_regr().
%   params:       Parameters for analysis and plotting.

if iscell(input)   %input consists of results from >1 cell (a cell array)
    nPredictor = numel(input{1}.beta);
    for k=1:numel(input)
        for j=1:nPredictor
            beta(:,j,k) = input{k}.beta{j};
        end
    end
    t_beta = input{1}.t_beta;
    beta_label = input{1}.beta_label;
else                   %input is from 1 cell only
    nPredictor = numel(input.beta);
    for j=1:nPredictor
        beta(:,j,1) = input.beta{j};
    end
    t_beta = input.t_beta;
    beta_label = input.beta_label;
end
    
colors = cbrewer('qual', 'Set1', nPredictor);

temp = median(beta,3);
ymin = nanmin(temp(:));
ymax = nanmax(temp(:));

figure;
for j = 1:nPredictor
    subplot(2,round(nPredictor/2),j); hold on;
    plot(t_beta,nanmedian(beta(:,j,:),3),'Color',colors(j,:));
%    plot([0 0],[ymin ymax],'k');
    title(beta_label{j});
    xlim(params.window);
    ylim([ymin ymax]);
    ylabel('GLM coefficient');
    xlabel('Time from event (s)');
end

end
